
### Create bucket
POST http://localhost:8080/create_bucket HTTP/1.1
Content-Type: application/json

{
  "description": "Description bucket 1",
  "name": "Name bucket 1",
  "aws_access_key_id": "Aws access key id bucket 1",
  "aws_secret_access_key": "Aws secret access bucket 1",
  "aws_region": "Aws region"

}


### List buckets
GET http://localhost:8080/get_buckets HTTP/1.1

### Fetch bucket
GET http://localhost:8080/get_bucket?id=703855ff-d928-4229-b3b6-463524c78f88



### Change data bucket
PUT http://localhost:8080/update_bucket

{
  "id": "dbbd2485-68a9-451d-ad68-02b2ca682204",
  "description": "Description bucket 1",
  "name": "Name bucket 1",
  "aws_access_key_id": "Aws access key id bucket 1",
  "aws_secret_access_key": "Aws secret access bucket 1",
  "aws_region": "Aws region"
}
