### Create owner
POST http://localhost:8080/create_owner HTTP/1.1
Content-Type: application/json

{
  "people_type": "F",
  "is_active": true,
  "bucket_id": "dbbd2485-68a9-451d-ad68-02b2ca682204",
  "Person": {
	  "first_name": "Claudiney",
    "last_name": "Veloso",
	  "email": "claudineyveloso@gmail.com",
	  "phone": "",
	  "cell_phone": "(31) 97100-0533"
  },
  "Address": {
    "public_place": "Rua Andesita, 594",
	  "complement": "",
	  "neighborhood": "União",
	  "city": "Belo Horizonte",
	  "state": "Minas Gerais",
	  "zip_code": "31170-480"
  }
}

### List owners
GET http://localhost:8080/get_owners HTTP/1.1

### Fetch owner
GET http://localhost:8080/get_owner?id=703855ff-d928-4229-b3b6-463524c78f88



### Change data owner
PUT http://localhost:8080/update_owner

{
  "people_type": "F",
  "is_active": true,
  "bucket_id": "dbbd2485-68a9-451d-ad68-02b2ca682204",
  "Person": {
	  "first_name": "Claudiney",
    "last_name": "Veloso",
	  "email": "claudineyveloso@gmail.com",
	  "phone": "",
	  "cell_phone": "(31) 97100-0533"
  },
  "Address": {
    "public_place": "Rua Andesita, 594",
	  "complement": "",
	  "neighborhood": "União",
	  "city": "Belo Horizonte",
	  "state": "Minas Gerais",
	  "zip_code": "31170-480"
  }
}
